# For building and uploading conda packages and environments
FROM stefco/llama-env:py37

ARG DOCKER_META
USER root
COPY requirements-dev.txt /home/llama/requirements-dev.txt
RUN apk --no-cache add vim make rsync texlive-full \
    && su llama -c 'bash -i -c " \
        conda install anaconda-client conda-build \
            && pip install -r /home/llama/requirements-dev.txt \
            && pip install git+https://github.com/stefco/pypiprivate.git \
            && rm -r ~/miniconda3/pkgs \
    "' \
    && echo "${DOCKER_META}" >>/docker-meta.yml \
    && rm /home/llama/requirements-dev.txt
USER llama
