# For building and uploading conda packages and environments
FROM stefco/llama-env:py36

ENV DOCKER_VERSION=0.0.9
ENV DOCKER_REPO=stefco/llama-dev
ENV DOCKER_TAG=py36
USER root
COPY requirements-dev.txt /home/llama/requirements-dev.txt
RUN apk --no-cache add vim make rsync git texlive-full openssh \
    && su llama -c 'bash -i -c " \
        conda install anaconda-client conda-build \
            && pip install -r /home/llama/requirements-dev.txt \
            && pip install git+https://github.com/stefco/pypiprivate.git \
            && rm -r ~/miniconda3/pkgs \
    "' \
    && rm /home/llama/requirements-dev.txt
USER llama
