# For building and uploading conda packages and environments
FROM stefco/llama-env:py37

USER root
COPY requirements-dev.txt /home/llama/requirements-dev.txt
RUN su llama -c 'bash -i -c " \
        conda install anaconda-client conda-build \
            && pip install -r /home/llama/requirements-dev.txt \
            && pip install git+https://github.com/stefco/pypiprivate.git \
            && rm -r ~/miniconda3/pkgs \
    "' \
    && apk --no-cache add vim make rsync git \
    && rm /home/llama/requirements-dev.txt
USER llama
